version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Lerna Bootstrap
          command: |
            npm run bootstrap
      - run:
          name: Run the Tests
          command: |
            npm run test
